name: ${project.name}
version: ${project.version}
main: dev.flur.ranks.Ranks
api-version: '1.21'
authors:
  - 'flurbudurbur'

depend:
  - Vault

softdepend:
  - PlaceholderAPI
  - LuckPerms

libraries:
  - org.apache.commons:commons-lang3:3.20.0

commands:
  ranks:
    description: "View available ranks or manage the plugin"
    usage: "/ranks [reload [full]]"
  rankup:
    description: "Rank up to the next available rank"
    usage: "/rankup [rank]"
  requirements:
    description: "View requirements for ranks"
    usage: "/requirements [rank]"
    aliases:
      - reqs

permissions:
  ranks.admin.reload:
    description: "Allows reloading the ranks plugin configuration"
    default: op